### ISSUE TITLE
Set<String> support

### ISSUE THREAD

**Issue by lupajz** [martino2k6/StoreBox#7]
Haven't had much time trying out your lib yet, but I like the idea. Just gave source a look but haven't noticed support for Set<String> set & get operations.

**Comment by martino2k6** [comment]
You're correct. I have omitted Set<String> support on purpose as the library provides the implementation from the interface at runtime, at which point the parametrised types are no longer available due to Java's type erasure. Therefore I have no guarantee that the caller has parametrised the Set with a String as opposed to some other type. I will however include support for it when I will complete custom type support (#3).

**Comment by martino2k6** [comment]
This has now been implemented as part of #3.
